name: 'Terraform Deployment'
on:
  push:
    tags:
    - '**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_g73_techchallenge_db_username: ${{ secrets.DB_USERNAME }}
  TF_VAR_g73_techchallenge_db_password: ${{ secrets.DB_PASSWORD }}

jobs:
  plan:
    name: 'Terraform plan'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.4

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan
  
  apply:
    name: 'Terraform plan'
    runs-on: ubuntu-latest
    needs: plan
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.4

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve